package com.lee.blog.gatewayimpl;

import com.alibaba.cola.logger.Logger;
import com.alibaba.cola.logger.LoggerFactory;
import com.lee.blog.common.event.DomainEventPublisher;
import com.lee.blog.domain.gateway.MetricGateway;
import com.lee.blog.domain.metrics.MainMetricType;
import com.lee.blog.domain.metrics.MetricItem;
import com.lee.blog.domain.metrics.SubMetric;
import com.lee.blog.domain.metrics.SubMetricType;
import com.lee.blog.domain.metrics.appquality.AppMetric;
import com.lee.blog.domain.metrics.appquality.AppMetricItem;
import com.lee.blog.domain.metrics.devquality.BugMetric;
import com.lee.blog.domain.metrics.devquality.BugMetricItem;
import com.lee.blog.domain.metrics.techcontribution.*;
import com.lee.blog.domain.metrics.techinfluence.*;
import com.lee.blog.dto.domainevent.MetricItemCreatedEvent;
import com.lee.blog.gatewayimpl.database.MetricMapper;
import com.lee.blog.gatewayimpl.database.dataobject.MetricDO;
import com.lee.blog.gatewayimpl.rpc.AppMetricMapper;
import com.lee.blog.gatewayimpl.rpc.BugMetricMapper;
import com.lee.blog.gatewayimpl.rpc.dataobject.AppMetricDO;
import com.lee.blog.gatewayimpl.rpc.dataobject.BugMetricDO;
import com.lee.blog.convertor.MetricConvertor;
import org.springframework.beans.BeanUtils;
import org.springframework.stereotype.Component;

import javax.annotation.Resource;
import java.util.ArrayList;
import java.util.List;

/**
 * MetricGatewayImpl
 *
 * @author Frank Zhang
 * @date 2020-07-02 12:20 PM
 */
@Component
public class MetricGatewayImpl implements MetricGateway {
    private static Logger logger = LoggerFactory.getLogger(MetricGatewayImpl.class);

    @Resource
    private MetricMapper metricMapper;

    @Resource
    private BugMetricMapper bugMetricMapper;

    @Resource
    private AppMetricMapper appMetricMapper;

    @Resource
    private DomainEventPublisher domainEventPublisher;


    public void save(MetricItem metricItem){
        MetricDO metricDO = MetricConvertor.toDataObject(metricItem);

        metricMapper.create(metricDO);

        logger.debug("AutoGeneratedId: "+metricDO.getId());
        MetricItemCreatedEvent metricItemCreatedEvent = new MetricItemCreatedEvent();
        metricItemCreatedEvent.setId(metricDO.getId());
        metricItemCreatedEvent.setUserId(metricDO.getUserId());
        metricItemCreatedEvent.setMainMetricType(metricDO.getMainMetric());
        domainEventPublisher.publish(metricItemCreatedEvent);
    }


    public List<SubMetric> listByTechContribution(String userId){
        List<MetricDO> metricDOList = metricMapper.listByMainMetric(userId, MainMetricType.TECH_CONTRIBUTION.getMetricCode());
        RefactoringMetric refactoringMetric = new RefactoringMetric();
        MiscMetric miscMetric = new MiscMetric();
        CodeReviewMetric codeReviewMetric = new CodeReviewMetric();
        List<SubMetric> subMetricList = new ArrayList<>();
        subMetricList.add(refactoringMetric);
        subMetricList.add(miscMetric);
        subMetricList.add(codeReviewMetric);
        metricDOList.forEach(metricDO -> {
            String json = metricDO.getMetricItem();
            switch (SubMetricType.valueOf(metricDO.getSubMetric())){
                case Refactoring:
                    refactoringMetric.addMetricItem(RefactoringMetricItem.valueOf(json));
                    break;
                case Misc:
                    miscMetric.addMetricItem(MiscMetricItem.valueOf(json));
                    break;
                case CodeReview:
                    codeReviewMetric.addMetricItem(CodeReviewMetricItem.valueOf(json));
                    break;
                default:
                    logger.error("illegal SubMetric type: " + metricDO.getSubMetric());
            }
        });
        return subMetricList;
    }

    public List<SubMetric> listByTechInfluence(String userId){
        List<MetricDO> metricDOList = metricMapper.listByMainMetric(userId, MainMetricType.TECH_INFLUENCE.getMetricCode());
        ATAMetric ataMetric = new ATAMetric();
        SharingMetric sharingMetric = new SharingMetric();
        PatentMetric patentMetric = new PatentMetric();
        PaperMetric paperMetric = new PaperMetric();
        List<SubMetric> subMetricList = new ArrayList<>();
        subMetricList.add(ataMetric);
        subMetricList.add(sharingMetric);
        subMetricList.add(patentMetric);
        subMetricList.add(paperMetric);
        metricDOList.forEach(metricDO -> {
            String json = metricDO.getMetricItem();
            switch (SubMetricType.valueOf(metricDO.getSubMetric())){
                case ATA:
                    ataMetric.addMetricItem(ATAMetricItem.valueOf(json));
                    break;
                case Sharing:
                    sharingMetric.addMetricItem(SharingMetricItem.valueOf(json));
                    break;
                case Patent:
                    patentMetric.addMetricItem(PatentMetricItem.valueOf(json));
                    break;
                case Paper:
                    paperMetric.addMetricItem(PaperMetricItem.valueOf(json));
                default:
                    logger.error("illegal SubMetric type: " + metricDO.getSubMetric());
            }
        });
        return subMetricList;
    }

    public BugMetric getBugMetric(String userId){
        BugMetricDO bugMetricDO = bugMetricMapper.getByUserId(userId);
        BugMetricItem bugMetricItem = new BugMetricItem(bugMetricDO.getBugCount(), bugMetricDO.getCheckInCodeCount());
        BugMetric bugMetric = new BugMetric();
        bugMetric.addMetricItem(bugMetricItem);
        return bugMetric;
    }

    public AppMetric getAppMetric(String userId){
        List<AppMetricDO> appMetricDOList = appMetricMapper.listByUserId(userId);
        AppMetric appMetric = new AppMetric();
        appMetricDOList.forEach(appMetricDO -> {
            AppMetricItem appMetricItem = new AppMetricItem();
            BeanUtils.copyProperties(appMetricDO, appMetricItem);
            appMetric.addMetricItem(appMetricItem);
        });
        return appMetric;
    }
}
